### ISSUE TITLE
Contrast for highlight vs selection

### ISSUE THREAD

**Issue by ennoucas** [francmarin98/jetbrains-moonlight-theme#1]
Hi Francisco! 

Thanks for your amazing theme. I've been using it for months now and it's really a great one! 

There is one thing though I'm struggling with: colours between highlight and selection seems to be inverted. Highlight colour is more visible than selection which confuses me a lot. Here's an example: 

**Highlight colour (cursor in the middle of `findByRole`)**:
<img width="709" alt="Screenshot 2022-07-08 at 08 08 44" src="https://user-images.githubusercontent.com/5324471/177936904-cc2741c1-4a6d-4a77-97b1-900b411a39e3.png">

**Selection colour (the first`findByRole` is selected)**:
<img width="719" alt="Screenshot 2022-07-08 at 08 10 45" src="https://user-images.githubusercontent.com/5324471/177937261-1f1d4cab-8cd7-4d53-aa73-033aef719e12.png">

As you can see, it's really hard to see that the first findByRole is selected. It seems that it's actually the second one. What do you think?

Thanks, 
Lucas

**Comment by franmc01** [comment]
First of all, thank you very much for your support.

Regarding what you mention, you are right, you are inverted, I think I made a small mistake, in the next update with support for the new UI :D

**Comment by ennoucas** [comment]
Hi @francmarin98 I don't see any new release for this one. Do you plan to release it?

**Comment by franmc01** [comment]
Yes friend, give me a few days please. If you would like to collaborate in the improvement of success without fear!

**Comment by ennoucas** [comment]
Of course not in a rush at all! I was just wondering as you closed the issue.

**Comment by franmc01** [comment]
![image](https://user-images.githubusercontent.com/50973629/181259565-24fd5d98-7c77-4ef9-8c62-ab29656cd98e.png)

Update is comming!!

**Comment by ennoucas** [comment]
Hi @francmarin98. I saw your update thanks! Is there a way to make it available for 2022.1 and not only for 2022.2 versions?

**Comment by ennoucas** [comment]
Tested! Works like a charm :)
