### ISSUE TITLE
Sponsor links broken

### ISSUE THREAD

**Issue by ellierider** [francmarin98/jetbrains-moonlight-theme#10]
Hi! I noticed that your sponsor links are broken in the README. It looks like maybe you changed your GitHub username but forgot to update your links. Also, the link to your GitHub page is broken on the JetBrains plugin site: https://plugins.jetbrains.com/vendor/523271e3-0c24-492c-93aa-e01e9a49ae7a

**Comment by franmc01** [comment]
Thanks for the information, you are absolutely right. There I updated you =)

**Comment by ellierider** [comment]
Nice! I don't see it yet but I will keep an eye out.
