### ISSUE TITLE
Update the plugin to be compatible with new versions of Jetbrains IDEs

### ISSUE THREAD

**Issue by franmc01** [francmarin98/jetbrains-moonlight-theme#12]
Hello guys, could you help me with the update?
@petehouston  @abdelhalimjean

**Comment by abdelhalimjean** [comment]
what do you mean? the latest version 1.6 is compatible with the latest Jetbrains IDEs version (2023.3.5)

**Comment by KostiantynPopovych** [comment]
Hey guys, I'm using Ultimate edition 2024.1, and it rejects me from installing the theme :(

Thank you in advance.

btw, the theme is awesome!

![Screenshot 2024-04-06 at 10 32 12 PM](https://github.com/franmc01/jetbrains-moonlight-theme/assets/31954184/ca26593b-42e9-4c15-9d1f-838407a0ca2f)

**Comment by abdelhalimjean** [comment]
@franmc01 can you please publish the latest version to the jetbrains plugin store

@KostiantynPopovych if you're in a hurry you can download the jar for v1.7 from my fork and install it
https://github.com/abdelhalimjean/jetbrains-moonlight-theme/releases/tag/v1.7

**Comment by franmc01** [comment]
I already sent it but: JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.

**Comment by franmc01** [comment]
It is now available
https://plugins.jetbrains.com/plugin/18943-moonlight-dark-theme
