### ISSUE TITLE
Do not work with Intellij 2022.3.1

### ISSUE THREAD

**Issue by iSnakeBuzz** [francmarin98/jetbrains-moonlight-theme#2]
Hi, Intellij have updated they IDE and make some changes into the UI, this theme seems to be not working with those changes.

**Comment by franmc01** [comment]
Working on that my friend, this week it comes out: D

**Comment by Kent55** [comment]
@francmarin98 any update on this?

**Comment by franmc01** [comment]
![image](https://user-images.githubusercontent.com/50973629/219815305-f77d639d-2a18-4bcc-a9cc-4ca0e1294008.png)

Update ready, they will forgive the delay =)

**Comment by franmc01** [comment]
all collaboration is welcome, greetings

**Comment by Kent55** [comment]
@francmarin98 fab, thanks for the release! Might I suggest you also publish the releases in their compressed archives here, too, so that they can be installed manually should one wish to; and when awaiting publication on the Jetbrains marketplace, they're at least still available etc.

**Comment by franmc01** [comment]
@Kent55 Good suggestion, and to be honest if I missed that.

Enjoy: https://github.com/francmarin98/jetbrains-moonlight-theme/releases/tag/v1.3

**Comment by franmc01** [comment]
Hello Everyone,

My apologies for the delay, and thank you for your patience. 🙏

I'm excited to share that the update has now been published and is under review. 🚀

![image](https://github.com/frankops11/jetbrains-moonlight-theme/assets/50973629/533c9a09-8d25-490b-a97c-e6d94841cd8e)

Please feel free to try it out and share any feedback or issues you may encounter here. 🐞📝

Thank you for your support and understanding during this time.

Best Regards,
Francisco Marin
