### ISSUE TITLE
Didn't find the theme on marketplace

### ISSUE THREAD

**Issue by userAugustos** [francmarin98/jetbrains-moonlight-theme#3]
Is the theme still alive? Or never registered?
Is it based on [atomiks moonlight theme for vscode](https://github.com/atomiks/moonlight-vscode-theme)?

**Comment by franmc01** [comment]
![image](https://user-images.githubusercontent.com/50973629/219815788-c150c3db-019b-4486-8471-be586bdc4bc9.png)
![image](https://user-images.githubusercontent.com/50973629/219815805-65614dc8-c0fa-453a-a6e7-6882e389ec32.png)

Update ready, they will forgive the delay =)

**Comment by franmc01** [comment]
Regarding the question, yes friend. It's inspired by that theme, it's one of my favorites in vscode :)

**Comment by franmc01** [comment]
Any improvement that you consider ideal, will be heard and if you would like to collaborate, too :)
