### ISSUE TITLE
New UI, Running is difficult to read

### ISSUE THREAD

**Issue by zbee** [francmarin98/jetbrains-moonlight-theme#4]
![image](https://user-images.githubusercontent.com/1582821/226239205-c69eb686-b042-490a-b0ec-567c0b9dfe04.png)

As you can see, it is rather difficult to see the Run area along the top of the window in the new UI while the app is actually running.

![image](https://user-images.githubusercontent.com/1582821/226240013-d59be46d-5f12-4810-9d45-8597b56281a7.png)

It does look quite good when the app is not running, though a background color of some sort to give it shape would be welcome.

**Comment by franmc01** [comment]
Give me two days please

**Comment by zbee** [comment]
It is now also incompatible with 2023.1, most of the new UI is no longer styled.

**Comment by micate** [comment]
> It is now also incompatible with 2023.1, most of the new UI is no longer styled.

Not published yet ?
https://plugins.jetbrains.com/plugin/18943-moonlight-dark-theme

**Comment by franmc01** [comment]
The truth is that I haven't published it yet, I had a preview of the color correction but Jetbrains published its new release and I see that there have been certain changes that I have to reconsider and check that everything is correct. I promise to launch it from here to Monday, please be patient. Thanks for the support :)

**Comment by franmc01** [comment]
The time has come, any improvement tip is well accepted. At the moment it is under review by Jetbrains but you can download it extra officially from here.

https://github.com/francmarin98/jetbrains-moonlight-theme/releases/tag/v1.4
