### ISSUE TITLE
Not updated in the marktplace

### ISSUE THREAD

**Issue by userAugustos** [francmarin98/jetbrains-moonlight-theme#7]
![image](https://github.com/t1fmarin/jetbrains-moonlight-theme/assets/47693479/8b129d1d-d6f9-4773-b9fa-e62e8b308526)

I See that has a change 3 weeks ago, that allow compatible with the 2023.2, but it still doesn't appears on the marketplace, anyway can help with it?

**Comment by franmc01** [comment]
Hello Everyone,

My apologies for the delay, and thank you for your patience. 🙏

I'm excited to share that the update has now been published and is under review. 🚀

![image](https://github.com/frankops11/jetbrains-moonlight-theme/assets/50973629/533c9a09-8d25-490b-a97c-e6d94841cd8e)

Please feel free to try it out and share any feedback or issues you may encounter here. 🐞📝

Thank you for your support and understanding during this time.

Best Regards,
Francisco Marin
