### ISSUE TITLE
Not available on 2023.3.1

### ISSUE THREAD

**Issue by zbee** [francmarin98/jetbrains-moonlight-theme#8]
2023.3.1 is here, and Moonlight does not support it.

You may check out [this other theme](https://github.com/rmehri01/onenord-jetbrains), it does not get updated every release but it works every release.

**Comment by zbee** [comment]
@frankops11 Just wanted to follow up on this now that we've got 2023.3.2

**Comment by nguyenann13** [comment]
Looking to get this theme supported in 2023.3.2 as well...please

**Comment by abdelhalimjean** [comment]
if anyone wants support for newer versions, i have the latest 2023.3.2 build on my fork [https://github.com/abdelhalimjean/jetbrains-moonlight-theme](https://github.com/abdelhalimjean/jetbrains-moonlight-theme) you can install the jar file or build it yourself from the source.

i made a pull request, waiting for it to be merged

@nguyenann13 @zbee
